pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
		        bat 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: ''**/target/*.war'
					echo "Now Archived the Artifacts...."
                }
            }
        }
  
    }
}