pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
				bat 
                bat 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: 'java-tomcat-sample/*.war'
					echo "Now Archived the Artifacts...."
                }
            }
        }
  
    }
}